name: CI Automation Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  api-tests:
    name: API Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Give gradlew execute permission
        run: chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run API Tests
        run: ./gradlew apiTest

  web-tests:
    name: Web UI Tests
    runs-on: ubuntu-latest
    env:
      CI_HEADLESS: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Give gradlew execute permission
        run: chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Google Chrome stable
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb

      - name: Check Chrome version
        run: google-chrome --version

      - name: Run Web UI Tests
        run: ./gradlew webTest
